### ISSUE TITLE
Could you provide the dataset link?

### ISSUE THREAD

**Issue by guotong1988** [donglixp/lang2logic#10]
Thank you very much @donglixp

**Comment by jorpilo** [comment]
You have all the datasets used for training/testing at this link:
http://homepages.inf.ed.ac.uk/s1478528/lang2logic/

**Comment by mansoor49** [comment]
The link does not include the IFTTT dataset used in paper. Please provide this also.

**Comment by zbyrn** [comment]
The link is now 404. Could you provide the updated link?

**Comment by donglixp** [comment]
> The link is now 404. Could you provide the updated link?

Fixed in https://github.com/donglixp/lang2logic/commit/eef9c70a10a8d804cc3cab0ac0986f47a8761cd6
