### ISSUE TITLE
Modifying ClassNLLCriterion.cu

### ISSUE THREAD

**Issue by avinash2692** [donglixp/lang2logic#3]
Replacing `ClassNLLCriterion.cu` in `~/torch/extra/cunn/lib/THCUNN/` throws up errors :
```
/u/<user>/torch/extra/cunn/lib/THCUNN/ClassNLLCriterion.cu(126): error: identifier "THCRealTensor_checkGPU" is undefined

/u/<user>/torch/extra/cunn/lib/THCUNN/ClassNLLCriterion.cu(130): error: identifier "THCRealTensor_checkGPU" is undefined

/u/<user>/torch/extra/cunn/lib/THCUNN/ClassNLLCriterion.cu(198): error: identifier "THCRealTensor_checkGPU" is undefined

/u/<user>/torch/extra/cunn/lib/THCUNN/ClassNLLCriterion.cu(203): error: identifier "THCRealTensor_checkGPU" is undefined

4 errors detected in the compilation of "/tmp/tmpxft_0000621d_00000000-7_ClassNLLCriterion.cpp1.ii".
CMake Error at THCUNN_generated_ClassNLLCriterion.cu.o.cmake:267 (message):
  Error generating file
  /u/<user>/torch/extra/cunn/build/lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_ClassNLLCriterion.cu.o
```

**Comment by donglixp** [comment]
I think the problem is caused by the torch7 version, because torch7’s backend development is quite active. The torch7 version I used is c0e51b98acbb54e6655343a57152b6e711ffdc2b.

**Comment by avinash2692** [comment]
There seems to be some more errors in THCNN , is there a specific version of that required ?
Error Message : 
```
In file included from /u/<user>/torch/extra/cunn/lib/THCUNN/BatchNormalization.cu:1:0:
/u/<user>/torch/extra/cunn/lib/THCUNN/THCUNN.h:11:35: fatal error: THCGenerateFloatTypes.h: No such file or directory
 #include "THCGenerateFloatTypes.h"
                                   ^
compilation terminated.
CMake Error at THCUNN_generated_BatchNormalization.cu.o.cmake:206 (message):
  Error generating
  /u/<user>/torch/extra/cunn/build/lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_BatchNormalization.cu.o
make[2]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/./THCUNN_generated_BatchNormalization.cu.o] Error 1
make[1]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by donglixp** [comment]
The error seems to be caused by the problem of torch's install script. I am not sure what the specific reason is.

**Comment by saraswat** [comment]
Line 44 of install.sh ```git submodule update --init --recursive``` probably needs to be commented since our goal is to build the specific version c0e51b98acbb54e6655343a57152b6e711ffdc2b.

(Li -- we have not been able to get this to work yet.)

**Comment by saraswat** [comment]
Running with the git update commented out yields the following error, during the building of `rocks/cunn-scm-1.rockspec`. (BTW, we are building with CUDA v 8.0 for CUDA architecture 3.5.)

```
/u/vj0/torch/extra/cunn/lib/THCUNN/ClassNLLCriterion.cu(126): error: identifier "THCRealTensor_checkGPU" is undefined

/u/vj0/torch/extra/cunn/lib/THCUNN/ClassNLLCriterion.cu(130): error: identifier "THCRealTensor_checkGPU" is undefined

/u/vj0/torch/extra/cunn/lib/THCUNN/ClassNLLCriterion.cu(198): error: identifier "THCRealTensor_checkGPU" is undefined

/u/vj0/torch/extra/cunn/lib/THCUNN/ClassNLLCriterion.cu(203): error: identifier "THCRealTensor_checkGPU" is undefined

4 errors detected in the compilation of "/tmp/tmpxft_000006f4_00000000-7_ClassNLLCriterion.cpp1.ii".
CMake Error at THCUNN_generated_ClassNLLCriterion.cu.o.cmake:264 (message):
  Error generating file
  /u/vj0/torch/extra/cunn/build/lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_ClassNLLCriterion.cu.o
```

**Comment by donglixp** [comment]
The environment we used:

OS: Scientific Linux 7.1
GCC: 4.9.1 20140922 (Red Hat 4.9.1-10)
GPU: 980 or titan x
CUDA: 7.5

**Comment by donglixp** [comment]
I compress my torch folder and upload it to Google Drive.
Link: https://drive.google.com/file/d/0B8yp1gOBCztycW42eDNNaExWSlU/view?usp=sharing
Hope this would help.

**Comment by saraswat** [comment]
Thanks, with this torch folder I was able to make it work -- blew away cmake cache files, and ran install.sh. I am able to run lang2logic now... awesome!

**Comment by donglixp** [comment]
Great!

**Comment by Demolei** [comment]
hi @saraswat ,  I met the same problem as you. my question is how to remove the cmake cache files. I am a rookie for linux os. thanks!

**Comment by Demolei** [comment]
@saraswat  I solved it. just run clean.sh. Thanks!
