### ISSUE TITLE
 ./run.sh seq2seq jobqueries lstm problem

### ISSUE THREAD

**Issue by oanatifrea** [donglixp/lang2logic#6]
warning: '?.split' will not override existing symbol
loading vocabulary file: /home/oanat/lang2logic/seq2seq/jobqueries/data/vocab.q.txt	
loading vocabulary file: /home/oanat/lang2logic/seq2seq/jobqueries/data/vocab.f.txt	
loading text file...	
saving /home/oanat/lang2logic/seq2seq/jobqueries/data/map.t7	
saving /home/oanat/lang2logic/seq2seq/jobqueries/data/train.t7	
loading text file...	
saving /home/oanat/lang2logic/seq2seq/jobqueries/data/test.t7	
warning: '?.split' will not override existing symbol
using CUDA on GPU 0...	
Creating encoder	
Creating decoder	
number of parameters in the model: 396801	
loading data: train	
Starting training.	
/home/oanat/torch/extra/cunn/lib/THCUNN/ClassNLLCriterion.cu:57: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.
THCudaCheck FAIL file=/home/oanat/torch/extra/cutorch/lib/THC/generic/THCStorage.c line=32 error=59 : device-side assert triggered
/home/oanat/torch/install/bin/luajit: cuda runtime error (59) : device-side assert triggered at /home/oanat/torch/extra/cutorch/lib/THC/generic/THCStorage.c:32
stack traceback:
	[C]: at 0x7f4dca7647d0
	[C]: in function '__index'
	...nat/torch/install/share/lua/5.1/nn/ClassNLLCriterion.lua:50: in function 'forward'
	lstm/main.lua:211: in function 'opfunc'
	/home/oanat/torch/install/share/lua/5.1/optim/rmsprop.lua:35: in function 'rmsprop'
	lstm/main.lua:322: in function 'main'
	lstm/main.lua:373: in main chunk
	[C]: in function 'dofile'
	...anat/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670
warning: '?.split' will not override existing symbol
using CUDA on GPU 0...	
/home/oanat/torch/install/bin/luajit: cannot open </home/oanat/lang2logic/seq2seq/jobqueries/dump_lstm/model.t7> in mode r  at /home/oanat/torch/pkg/torch/lib/TH/THDiskFile.c:670
stack traceback:
	[C]: at 0x7fa0e1c44350
	[C]: in function 'DiskFile'
	/home/oanat/torch/install/share/lua/5.1/torch/File.lua:405: in function 'load'
	lstm/sample.lua:168: in main chunk
	[C]: in function 'dofile'
	...anat/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670

**Comment by donglixp** [comment]
Hi @oanatifrea ,

Thanks for your attention to our work! I am afraid it’s caused by the version of torch7.

I uploaded the torch7 (c0e51b98acbb54e6655343a57152b6e711ffdc2b) to GDrive. It can be downloaded from: https://drive.google.com/file/d/0B8yp1gOBCztycW42eDNNaExWSlU/view?usp=sharing .

You can unzip the file, and then run:
```
clean.sh
install.sh
```

Thanks!
