### ISSUE TITLE
About replacing ClassNLLCriterion.cu 

### ISSUE THREAD

**Issue by lachao** [donglixp/lang2logic#7]
Hi, 

     Thanks for sharing this project, it is quite interesting ! 
I am new to Torch

Currently I follow the setup steps in the Readme.md
I got one issue: about replacing ClassNLLCriterion.cu 

The previous commands are done
[Done] git clone https://github.com/torch/distro.git ~/torch --recursive 
[Done] cd ~/torch; bash install-deps;

But after  I want to replace
Replace ~/torch/extra/cunn/lib/THCUNN/ClassNLLCriterion.cu with the one in the ./install folder.

there is only one file "install.log" inside the install folder
I didn't see the ClassNLLCriterion.cu you mention ?
(Did I got something wrong before this step)

I continued running the ./install.sh, got the error message as below

Prefix set to /home/chaoying/torch/install
Installing Lua version: LUAJIT21
Inconsistency detected by ld.so: dl-version.c: 224: _dl_check_map_versions: Assertion `needed != ((void *)0)' failed!

Could you help me about this issue :)
Thank you very much

**Comment by donglixp** [comment]
Hi @ChaoyingWu ,

Thanks for your attention to our work! I am afraid it’s caused by the version of torch7.

I uploaded the torch7 (c0e51b98acbb54e6655343a57152b6e711ffdc2b) to GDrive. It can be downloaded from: https://drive.google.com/file/d/0B8yp1gOBCztycW42eDNNaExWSlU/view?usp=sharing .

You can unzip the file, and then run:
```
clean.sh
install.sh
```

Thanks!

**Comment by lachao** [comment]
Hi, Li Dong

Thanks for replying me!
Currently I still encounter the same problems after I replace torch with the same link what you share
My steps
(1) rm -r torch (remove the original torch files)
(2) download torch7 from GDrive
(3) enter torch folder & execute
     . sh clean.sh
     . sh install.sh

I got the message as the same as the previous error
Installing Lua version: LUAJIT21
Inconsistency detected by ld.so: dl-version.c: 224: _dl_check_map_versions: Assertion `needed != ((void *)0)' failed!

Could you give me any further suggestion :)

Thanks!
