### ISSUE TITLE
I've replaced the 'ClassNLLCriterion.cu' to the right place,  but it's still wrong,  details are as follows:

### ISSUE THREAD

**Issue by ldxbaby756** [donglixp/lang2logic#8]
/home/autonlp/torch/extra/cunn/lib/THCUNN/ClassNLLCriterion.cu:57: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.
THCudaCheck FAIL file=/home/autonlp/torch/extra/cutorch/lib/THC/generic/THCStorage.c line=32 error=59 : device-side assert triggered
/home/autonlp/torch/install/bin/luajit: cuda runtime error (59) : device-side assert triggered at /home/autonlp/torch/extra/cutorch/lib/THC/generic/THCStorage.c:32
stack traceback:
	[C]: at 0x7ff0f81c2c10
	[C]: in function '__index'
	...nlp/torch/install/share/lua/5.1/nn/ClassNLLCriterion.lua:50: in function 'forward'
	attention/main.lua:221: in function 'opfunc'
	/home/autonlp/torch/install/share/lua/5.1/optim/rmsprop.lua:35: in function 'rmsprop'
	attention/main.lua:347: in function 'main'
	attention/main.lua:399: in main chunk
	[C]: in function 'dofile'
	...onlp/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x004064f0

**Comment by donglixp** [comment]
Thanks for your attention to our work! I am afraid it’s caused by the version of torch7.

I uploaded the torch7 (c0e51b98acbb54e6655343a57152b6e711ffdc2b) to GDrive. It can be downloaded from: https://drive.google.com/file/d/0B8yp1gOBCztycW42eDNNaExWSlU/view?usp=sharing .

You can unzip the file, and then run:

```bash
clean.sh
install.sh
```

Thanks!

**Comment by ayushidalmia** [comment]
@donglixp What is the version of cunn and cutorch you have used?

**Comment by donglixp** [comment]
@ayushidalmia CUDA: 7.5
